export enum DangerType {
  Other = 0,
  Traffic = 1,
  AggressiveDogs = 2,
  PoisonedBait = 3,
  PoorLighting = 4,
  Crime = 5,
  WildAnimals = 6,
  UnfencedAreas = 7,
  BrokenGlass = 8,
  StrayDogs = 9,
  ConstructionZones = 10,
  LoudNoises = 11,
  OvercrowdedAreas = 12,
  UncleanAreas = 13,
  ToxicPlants = 14,
  HighCrimeRate = 15,
  PoorSurfaceConditions = 16,
  Snakes = 17,
  Ticks = 18,
  Trash = 19
}